trigger:
- main

variables:
  azureSubscriptionServiceConnection: 'AzureSubscription'
  azureContainerRegistryName: 'oliverlo'
  containerImageName: 'docfx-demo'
  containerTag: '$(Build.BuildNumber)'
  appNameDev: 'docfx-demo'
  appResourceGroupNameDev: 'docfx_sample_rg'

stages:
  - stage: build
    displayName: Build DocFx Container
    jobs:
      - job: build
        displayName: Build
        pool:
          vmImage: windows-latest
        steps:
        - task: AzureCLI@2
          displayName: Build DocFx Container
          inputs:
            azureSubscription: $(azureSubscriptionServiceConnection)
            scriptType: ps
            scriptPath: Build-DocFX.ps1
            arguments: > # Use this to avoid newline characters in multiline string
              -DocFXJson src\docfx.json
              -RegistryName $(azureContainerRegistryName)
              -ImageName $(containerImageName)
              -Tag $(containerTag)

  - stage: deploy
    displayName: Deploy 
    dependsOn: build
    jobs:
      - deployment: deploy_dev
        displayName: Deploy dev
        pool: 
          vmImage: 'ubuntu-latest'
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureCLI@2
                  displayName: Build DocFx Container
                  inputs:
                    azureSubscription: $(azureSubscriptionServiceConnection)
                    scriptType: ps
                    scriptPath: Build-DocFX.ps1
                    arguments: > # Use this to avoid newline characters in multiline string
                      -RegistryName $(azureContainerRegistryName)
                      -ImageName $(containerImageName)
                      -Tag $(containerTag)
                      -AppServiceName $(appNameDev)
                      -AppServiceResourceGroupName $(appResourceGroupNameDev)